### PR TITLE
Docker container build optimization and rework

### PR DESCRIPTION
**Pull request by localagi**
# Description

* moving Dockerfiles into separate dir, renaming for convention
  * fixing docker-compose paths
* reuse docker containers for different build variants based on exact digest (e.g. for streamlit)
* downsize a simple docker build by 70% (running with cpu torch, omitting nvidia python deps)
* add builds for nvidia based docker container
* removed build for fastchat 3rd party service - see https://github.com/localagi/fastchat-docker
* automatically adds README to docker hub
* new **parameters** for reusable workflow
  * registry readme file (docker hub)
  * tags
  * individual registry selection including image name generation
  * push or not
  * ...
* Pull requests triggers end after basic build

## Motivation and Context

Make docker builds more widely available and lower entry level by sorting out following 
- usecases: run only with remote services, run on local cpu, run on local gpu, run third party service packed by us
- roles: users/testers, developers

More to come in regards to docker-compose when finishing the motivation and this step is working

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
@greengeckowizard please check here, if all your reqs are still met. 
reference: https://github.com/Josh-XT/Agent-LLM/pull/329

Maybe try out the latest containers on https://hub.docker.com/r/localagi/agent-llm-streamlit/tags

tag [test_rework_docker_builds] (avail in a few mins, this still running https://github.com/localagi/Agent-LLM/actions/runs/4985310949

**Comment by localagi** [comment]
@Josh-XT dunno why the docker login does not work on your repo.

**Comment by Josh-XT** [comment]
Might be. I can accept it if you want to see if that helps.

**Comment by localagi** [comment]
> Might be. I can accept it if you want to see if that helps.

Ok, cool!

**Comment by localagi** [comment]
@Josh-XT also worth having a look at the details. changed a lot. What is the link to your docker hub?

**Pull request merged**
