### PR TITLE
Revert "Bring back the dockerfiles"

### PR DESCRIPTION
**Pull request by localagi**
Reverts Josh-XT/Agent-LLM#342

Please dont have double docker files in the repo. It fucks things up. I try to streamline it really.

### CODE REVIEW

**Comment by localagi** [comment]
@Josh-XT also it's a bit de-motivational bc i don't know if the guy did something to the returned dockerfiles to do something.

Idea: I'd go review all the dev-ops stuff, you concentrate on the code? And just give input if you want something on the docker containers or something is not working.

**Comment by localagi** [comment]
and just to be clear: Dockerfiles are in docker/

**Comment by Josh-XT** [comment]
@greengeckowizard added them due to issues with arm64.

**Comment by localagi** [comment]
> I can merge to remove them, just want to make sure the arm64 stuff isn't lost if it isn't working in the dockerfiles in the docker folder, I am not sure personally since I don't use arm64. @greengeckowizard may need to confirm.
> 
> https://github.com/Josh-XT/Agent-LLM/pull/342/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557


Yeah, i asked him in the old PR to check. Due to the new structure of cascading, the `Dockerfile.streamlit` doesn't require extra additions. The original Dockerfile (btw the image) is re-used. I checked all his changes from 2d ago. I saw there is smth going on ;)

**Pull request merged**
