### PR TITLE
Fix some commands

### PR DESCRIPTION
**Pull request by hlohaus**
Add requets log to provider
Add gpt4free fallbacks
Refactor agent llm run
Add nested commands

We have to be careful not to send so many requests to the api.
You will then be blocked or it will cost a lot.

# Description

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by Josh-XT** [comment]
> Add requets log to provider Add gpt4free fallbacks Refactor agent llm run Add nested commands
> 
> We have to be careful not to send so many requests to the api. You will then be blocked or it will cost a lot.
> 
> # Description
> ## Motivation and Context
> ## How has this been tested?
> ## Screenshots (if appropriate)
> ## Types of changes
> Changes visible to users:
> 
> * [ ]  **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
> * [ ]  **New feature** (prefix: `feat` - non-breaking change which adds functionality)
> * [ ]  **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)
> 
> Internal changes:
> 
> * [ ]  **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
> * [ ]  **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
> * [ ]  **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)
> 
> ## Checklist
> * [ ]  My code follows the code style of this project and passes `yarn run lint`.
> * [ ]  My change requires a change to the documentation.
> * [ ]  My change works!

Still reviewing, can you format with the `Python Black` vscode extension so that it will pass the linting?

**Comment by Josh-XT** [comment]
You also have a bunch of old code that was changed in your AgentLLM.py.

**Comment by Josh-XT** [comment]
Accepted many of your changes in this commit: https://github.com/Josh-XT/Agent-LLM/commit/593ddaa042794d71e8ae5c5846f7277406d95dc3

AgentLLM.py and Agent.py need work before I can merge those and I am worried about merging the Commands.py changes without merging the AgentLLM.py changes.  If you're able to get rid of the conflicts, happy to still merge changes if they're useful and working. :)  Thank you!

**Comment by hlohaus** [comment]
Thanks. I will Take a look

**Pull request closed without merging**
