### PR TITLE
add missing path to urls

### LINKED ISSUE #182: Error when go to agent
### Description

In new version there is an error when user go to agent page (http://localhost:3000/agent/Agent-LLM)

Знімок екрана 2023-05-01 о 22 44 06

Promise { <pending> }
error - unhandledRejection: Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
error - Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
error - Error: connect ECONNREFUSED ::1:80
    at AxiosError.from (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/axios/lib/adapters/http.js:591:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/timur/Downloads/Agent-LLM-1.1.0-alpha/frontend/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}

### Steps to Reproduce the Bug

1. Run frontend
2. Run backend
3. Go to http://localhost:3000/agent/Agent-LLM 

### Expected Behavior

Goes to page without error

### Actual Behavior

Error occurs

### Additional Context / Screenshots

_No response_

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

### PR DESCRIPTION
**Pull request by samuzaffar99**
Potential fix for ECONNREFUSED error

# Description

This adds the missing paths in the URLs, avoiding redirects to localhost:80 for invalid links.

## Motivation and Context

Allows the frontend to communicate with the backend in cases where the link was previously invalid

Potentially fixes #182 , #184 , #188 , #189
## How has this been tested?
Only tested it on my system; after the changes, the agents page loads sometimes but no longer gives the error. Requesting testing by other users.

## Types of changes

Changes visible to users:

- [x] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by Josh-XT** [comment]
Thanks!

**Comment by dany-on-demand** [comment]
I think this PR should be undone, it introduced a host of issues like #184. It references process.env all over the frontend which is not available in the browser for obvious reasons

**Comment by Josh-XT** [comment]
> I think this PR should be undone, it introduced a host of issues like #184. It references process.env all over the frontend which is not available in the browser for obvious reasons

Did your PR fix the issue this caused?

**Comment by samuzaffar99** [comment]
This PR was introduced after #189, the process.env variable was already being referenced in the other files. In the files that didn't have the prefix, it was causing the aforementioned issues (hence I added the prefix).
Though I'm not a js dev, but shouldn't the expression evaluate to the localhost string if it is null?
I do agree with you that there could probably be a better way of handling the urls.

**Pull request merged**
